version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://landingwise:password@db:5432/landingwise
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL:-http://localhost:3000}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env.local:/app/.env.local:ro

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=landingwise
      - POSTGRES_USER=landingwise
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U landingwise -d landingwise"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 